### ISSUE TITLE
树莓派1B 手机无法搜索到

### ISSUE THREAD

**Issue by wanglz111** [BonusCloud/BonusCloud-Node#21]
如题，树莓派刷了系统以后 无法连接

**Comment by bg4vrg** [comment]
同样问题。估计不支持。另外居然不提供用户名和密码，很奇怪

**Comment by bilang** [comment]
可以在以下两个渠道沟通：
BonusCloud  博纳云 中文电报群：
https://t.me/bonuscloudcn
QQ群：
540325227
谢谢
