### ISSUE TITLE
华硕AC86U安装Bonuscloud插件后无法使用

### ISSUE THREAD

**Issue by xiaoxihu2017** [BonusCloud/BonusCloud-Node#22]
安装 BonusCloud-Node/aarch64-merlin/bxc.tar.gz 后，出现如下画面，没有输入账号的地方。输入码后提示格式不正确
![image](https://user-images.githubusercontent.com/31083939/47537056-3eaed600-d8f6-11e8-977e-63624331bc83.png)

**Comment by bilang** [comment]
目前这个版本是测试版本，正式版本尽快推出

**Comment by bilang** [comment]
可以使用了
