### ISSUE TITLE
aarch32安装脚本有bug

### ISSUE THREAD

**Issue by ziyuedi** [BonusCloud/BonusCloud-Node#31]
第72行ret=\`which apt;echo $?\`

其中`which apt;echo $?`
输出为
`/usr/bin/apt`
`0`
bash会报参数太多
应改为ret=\`which apt > /dev/null;echo $?\`
第42行同理
或者直接用if判断文件是否存在/用dpkg等包管理器

**Comment by qinghon** [comment]
非常感谢，已修改
