### ISSUE TITLE
salt安装非n1设备取ID报错

### ISSUE THREAD

**Issue by BonusCloud** [BonusCloud/BonusCloud-Node#47]
/install.sh: line 362: warning: command substitution: ignored null byte in input
生成配置文件id为_
saltconfig() {
    sed -i "/^id:/d" /etc/salt/minion
    echo "id: _" >> /etc/salt/minion
    /etc/init.d/salt-minion restart > /dev/null 2>&1
}

**Comment by qinghon** [comment]
请提供一下您的设备型号信息

**Comment by qinghon** [comment]
#48 salt 组件已弃用
