### ISSUE TITLE
armbian armv7 安装salt报错

### ISSUE THREAD

**Issue by BonusCloud** [BonusCloud/BonusCloud-Node#48]
* ERROR: Support for armhf packages at repo.saltstack.com is limited to Debian/Raspbian 8 platforms.
 * ERROR: You can try git installation mode, i.e.: sh bootstrap-salt.sh git v2017.7.2.
 * ERROR: It may be necessary to use git installation mode with pip and disable the SaltStack apt repository.
 * ERROR: For example:
 * ERROR:     sh bootstrap-salt.sh -r -P git v2017.7.2
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!

**Comment by qinghon** [comment]
salt 组件已弃用
